'''digit=set()

n=int(input("enter the number1"))
digit.add(int(n))
n=int(input("enter the number2"))
digit.add(int(n))
n=int(input("enter the number3"))
digit.add(int(n))
n=int(input("enter the number4"))
digit.add(int(n))
n=int(input("enter the number5"))
digit.add(int(n))
n=int(input("enter the number6"))
digit.add(int(n))
n=int(input("enter the number7"))
digit.add(int(n))
n=int(input("enter the number8"))
digit.add(int(n))
print(digit)'''

s=set()
s.add(18)
s.add("18")
print(s)
k=set()
k.add(20)
k.add(20.0)
k.add("20")
print(k)
print(len(k))
